version: '3.8'

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    # volumes:
    # - /Users/nazifcandurgut/.volumes/blog:/var/lib/postgresql
